import { ImageSourcePropType } from 'react-native';

export const images: { [key: string]: ImageSourcePropType } = {
  user: require('./user.png'),
  dayCare: require('./dayCare.png'),
  slide: require('./slide.png'),
  slide2: require('./slide2.png'),
  boarding: require('./boarding.png'),
  dog1:require('./dog1.png'),
  dog2:require('./dog2.png'),
  map:require('./map.png'),
  hotel:require('./hotel.png'),
  bulldog: require('./bulldog.png'),
    female: require('./female.png'),
    paw: require('./paw.png'),
    smileys: require('./smileys.png'),
    dog1: require('./dog1.png'),
    dog2: require('./dog2.png'),
    dog3: require('./dog3.png'),
    dog4: require('./dog4.png'),
    dog5: require('./dog5.png'),
    dog6: require('./dog6.png'),
    dog7: require('./dog7.png'),
    pfp: require('./pfp.png'),
    cover: require('./cover.png'),
    resturant: require('./resturant.png'),
    upload: require('./upload.png'),
    Visa: require('./Visa.png'),
    green: require('./green.png'),
    storedetail1: require('./storedetail1.png'),
    storedetail2: require('./storedetail2.png'),
    storedetail3: require('./storedetail3.png'),
    storedetail4: require('./storedetail4.png'),
    storedetail5: require('./storedetail5.png'),
    dogProfile: require('./dogProfile.png'),
    service1: require('./service1.png'),

};
